#!/bin/sh
set -eu

usage() {
	echo "usage: ${0##*/} [-n] [-c XDG_CONFIG_HOME]"
	exit 1
}

PRINT_ONLY=
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
while getopts "c:n" opt; do
	case $opt in
	  c) CONFIG_HOME="$OPTARG";;
	  n) PRINT_ONLY=1;;
	  *) usage;;
	esac
done

prefix=$(dirname `realpath $0`)
uid=`id -u`
uname=`uname`

if [[ $uid -ne 0 ]]; then
	echo "$0 needs id=0 to proceed, got id=$uid."
	exit 1
fi

if [ $PRINT_ONLY ]; then
	su $DOAS_USER -c "$prefix/term/install -n"
	su $DOAS_USER -c "$prefix/xorg/install -n"
	$prefix/pkg/install -n
else
	su $DOAS_USER -c "$prefix/term/install"
	su $DOAS_USER -c "$prefix/xorg/install"
	$prefix/pkg/install
fi
