#!/bin/sh
set -e
self=${0##*/}
prefix=$(dirname `realpath $0`)
uid=`id -u`
uname=`uname`

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

if [[ $uid -ne 0 ]]; then
	echo "$self needs id=0 to proceed, got id=$uid."
	exit 1
fi

usage() {
	echo "usage: $self [-n] [-c XDG_CONFIG_HOME]"
	exit 1
}

while getopts "n" opt; do
	case $opt in
	  n) PRINT_ONLY=1;;
	  *) usage;;
	esac
done

export PRINT_ONLY
su $DOAS_USER -cm "$prefix/term/install"
su $DOAS_USER -cm "$prefix/xorg/install"
$prefix/pkg/install
