#!/bin/sh
self=${0##*/}
prefix=$(dirname $(realpath $0))
uid=$(id -u)
uname=$(uname)
die() { echo "$1" && exit 1; }

[[ $uid -ne 0 ]]\
  && die "$self needs id=0 to proceed, got id=$uid"

[[ $uname -eq OpenBSD ]] && [[ -z $DOAS_USER ]]\
    && die "DOAS_USER not set"

while getopts 'n' opt; do
  case $opt in
  n) export PRINT_ONLY=1;;
  *) die "usage: $self [-n]";;
	esac
done

case $uname in
OpenBSD) user=$DOAS_USER;;
*) die "unsupported platform: $uname";;
esac

eval "${prefix}/pkg/install"
eval "su ${user} -cm '${prefix}/term/install; ${prefix}/xorg/install'"
