#!/usr/bin/env bash
_have() { type "$1" &>/dev/null; }

export BROWSER=firefox
export READER=firefox

xrdb -load\
  "${XDG_CONFIG_HOME:-"$HOME/.config"}/xdefaults" 2>/dev/null

xset b off
xset r rate 256 32

case "$(uname)" in
  Linux)
    rc="nm-applet blueberry-tray pasystray"
    for cmd in $rc; do
      if _have "$cmd"; then
        pidof -s "$cmd" || exec "$cmd" &
      fi
    done >/dev/null 2>&1
    [[ -d /run/systemd/system ]] && dbus-update-activation-environment\
      --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
    ;;
  *) ;;
esac

[[ -n "$xrdbpid" ]] && wait "$xrdbpid"
. /home/fm/xenv
xhi
exec i3
