#!/bin/sh

alias_gtg(){
	git add . &&\
		git commit -m "$1" &&\
		git push
}

alias cp="cp -i"
alias ccat="highlight -O xterm256"
alias lsd="du -hd 1"
alias ga="git add"
alias gc="git commit -m"
alias gl="git log --oneline --graph"
alias gp="git push"
alias gpa="git remote | xargs -L1 git push"
alias gs="git status -s"
alias gtg=alias_gtg
alias ls="colorls -GhF"
alias ll="colorls -GhFAl"
alias mv="mv -i"
alias nf="neofetch --uptime_shorthand tiny --ascii_distro OpenBSD_small --color_blocks off "
alias rm="rm -i"
alias s="dwmswallow $WINDOWID;"
alias t="tmux -uf ~/.config/tmux.conf"
alias vim="nvim"
