#!/bin/sh
alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gl="git log --oneline --graph"
alias gs="git status -s"
alias ll="ls -AFhl"
alias ua="ulimit -a"
alias ft="file"
alias gpa="git remote | xargs -L1 git push"
alias lsd="du -hd 1"

alias xcopy="xclip -selection c"
alias xpaste="xclip -selection c -o"

# overload defaults
alias ls="ls -AhF"
alias cp="cp -ir"
alias rm="rm -i"
alias mv="mv -i"
alias vim="nvim"
alias tmux="tmux -uf ~/.config/tmux.conf"
alias chrome="chrome --enable-unveil"
alias neofetch="neofetch --uptime_shorthand tiny --ascii_distro `uname`_small --color_blocks off "
