#!/usr/bin/env bash
# designed for bash 4.0+
case $- in
  *i*) ;; # interactive
  *) return ;;
esac

_have() { type "$1" &>/dev/null; }
_gitinfo() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-"$HOME/.local/state"}"
export XDG_BIN_HOME="${XDG_BIN_HOME:-"$HOME/.local/bin"}"

export PS1="\u@\h:\W\$(_gitinfo)\[\e[0;37m\]λ\[\e[0m\] "
export USER="${USER:-$(whoami)}"
export EDITOR=vi
export VISUAL=vi
export TERMINAL=xterm
export REPOS="$HOME/src"
export GHUSER=lacamera
export GHREPOS="$REPOS/github.com/$GHUSER"
export LC_COLLATE=C
#export CFLAGS="-Wall -Wextra -Werror -O0 -fsanitize=address -g"
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$XDG_BIN_HOME"
export GPG_TTY="$(tty)"
export LESS="-R"

# Stop history from saving duplicate commands
# and commands that begin with leading space
export HISTCONTROL=ignoreboth
export HISTSIZE=1024          # in memory
export HISTFILESIZE=4096      # on disk

m(){
  [[ -z "$@" ]] && return
  eval "$@" | less -R
}

path() {
  echo -e ${PATH//:/\\n}
}

pathappend() {
  for arg in "$@"; do
    [[ -d "$arg" ]] || continue
    arg="${arg%%/}"
    PATH="${PATH//":$arg:"/:}"
    PATH="${PATH#"$arg:"}"
    PATH="${PATH%":$arg"}"
    export PATH="${PATH:+"$PATH:"}$arg"
  done
}

pathprepend() {
  for arg in "$@"; do
    [[ -d "$arg" ]] || continue
    arg="${arg%%/}"
    PATH="${PATH//":$arg:"/:}"
    PATH="${PATH#"$arg:"}"
    PATH="${PATH%":$arg"}"
    export PATH="$arg${PATH:+":$PATH"}"
  done
}

pathprepend /bin\
  /sbin\
  /usr/bin\
  /usr/local/bin\
  /usr/local/sbin\
  "${XDG_BIN_HOME}"\
  /usr/bin/core_perl

_have cargo && pathappend "${HOME}/.cargo/bin"
_have cabal && pathappend "${HOME}/.cabal/bin"
_have ghcup && pathappend "${HOME}/.ghcup/bin"
_have go && pathappend "${GOBIN:-"$GOPATH/bin"}"

# Prevent Ctrl-s from stopping the terminal
stty stop undef

set -o vi
shopt -s histappend
shopt -s checkwinsize
shopt -s expand_aliases
shopt -s globstar
shopt -s dotglob
shopt -s extglob

unalias -a
alias cp="cp -ir"
alias rm="rm -i"
alias mv="mv -i"
_have tmux && alias tmux="tmux -f $XDG_CONFIG_HOME/tmux.conf"
_have exa && alias tree="exa -@ --tree"
# nvm doesn't work with prefix
_have nvm && unset npm_config_prefix
case "$(uname)" in
  Linux|Darwin)
    alias sudo="doas"
    alias ls="ls --color=always"
    alias grep="grep --color=always"
    _have bat && alias bat="bat --color=always"
    _have exa && alias exa="exa --color=always"
    _have yay && alias yay="yay --sudo doas"
    ;;
esac
