#!/bin/sh
set -e
prefix="$(dirname `realpath $0`)"
self=${0##*/}

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

usage() {
	echo "usage: term/$self [-n]"
	exit 1
}

while getopts "n" opt; do
	case $opt in
	  n) PRINT_ONLY=1;;
	  *) usage;;
	esac
done

find $prefix/ ! -name $self | while read src_abs; do
  src_rel=${src_abs##$prefix/}
  dest=$CONFIG_HOME/$src_rel
  if [ -d $src_abs ]; then
	[[ -n $PRINT_ONLY ]]\
	  && echo "mkdir -p $dest"\
	  || mkdir -p $dest
  else
	case $src_rel in
	  profile) dest=$HOME/.profile;;
	  exrc) dest=$HOME/.exrc;;
	  ssh_config) dest=$HOME/.ssh/config;;
	esac
	[[ -n $PRINT_ONLY ]]\
	  && echo "ln -fs $src_abs $dest"\
	  || ln -fs $src_abs $dest
  fi
done
