#!/bin/sh
set -e
self=${0##*/}
prefix="$(dirname `realpath $0`)/"

while getopts "n" opt; do
	case $opt in
	n) PRINT_ONLY=1;;
	*) printf "usage: term/%s [-n]\n" $self
	   exit 1;;
	esac
done

find $prefix ! -name $self | while read src_abs; do
  src_rel=${src_abs##$prefix}
  dest_abs=${XDG_CONFIG_HOME:-"$HOME/.config"}/$src_rel
  
  if [ -d $src_abs ]; then
	cmd="mkdir -p $dest_abs"
  else
    case $src_rel in
    gitconfig) dest_abs=~/.gitconfig;;
    profile) dest_abs=~/.profile;;
    exrc) dest_abs=~/.exrc;;
    ssh_config) dest_abs=~/.ssh/config;;
    esac
    cmd="ln -fs $src_abs $dest_abs"
  fi

  [[ -n $PRINT_ONLY ]]\
	&& printf "$cmd\n" || eval $cmd
done
