#!/bin/sh
PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games
export PATH HOME TERM

[ -f "$HOME/.config/env" ] && . "$HOME/.config/env"
[ -f "$HOME/.config/aliases" ] && . "$HOME/.config/aliases"

export XCURSOR_SIZE=32
export XCURSOR_PATH=/usr/local/lib/X11/icons
export XCURSOR_THEME=whiteglass
