#!/bin/sh
export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

# Source rest of rc if interactive session.
if [[ $- == *i* ]]; then
  [[ -n $XDG_CONFIG_HOME ]]\
    && pfx="$XDG_CONFIG_HOME/"\
    || pfx="$HOME/."

  export ENVRC="${ENVRC:-"${pfx}env"}"
  export ALIASRC="${ALIASRC:-"${pfx}aliases"}"

  [[ -f $ENVRC ]] && . $ENVRC
  [[ -f $ALIASRC ]] && . $ALIASRC

  mkdir -p $XDG_CACHE_HOME $XDG_CONFIG_HOME\
	  $XDG_DATA_HOME $XDG_STATE_HOME
fi
