#!/bin/sh
set -e

while getopts "nh" opt
do
  case "${opt}" in
    n) PRINT_ONLY=1;;
    *) usage; exit 1;;
  esac
done

self="${0##*/}"
rpath="$(realpath "$0")"
prefix="$(dirname "${rpath}")/"
xdg="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
find "${prefix}"\
  ! -name "${self}"\
  ! -name "README.md" | while read -r target
do
  c="${target##"${prefix}"}"
  c=${c#/}
  ln="${xdg}/${c}"
  if [ -f "$target" ]; then
    case "$c" in
      vi/exrc)         ln="${HOME}/.exrc";;
      git/gitconfig)   ln="${HOME}/.gitconfig";;
      bash/bashrc)     ln="${HOME}/.bashrc";;
      bash/profile)    ln="${HOME}/.profile";;
      bash/inputrc)    ln="${HOME}/.inputrc";;
      tmux/tmux.conf)  ln="${xdg}/tmux.conf";;
      ssh/*)      ln="${HOME}/.$c";;
      *);;
    esac
    path="$(dirname "${ln}")"
    cmd="mkdir -p ${path} && ln -fs ${target} ${ln}"
    if [ -n "$PRINT_ONLY" ]; then
      echo "$cmd"
    else
      eval "$cmd"
    fi
  fi
done
