#!/bin/sh
set -e

while getopts "nh" opt
do
  case "${opt}" in
    n) PRINT_ONLY=1;;
    h) usage; exit 0;;
    *) usage; exit 1;;
  esac
done

self="${0##*/}"
rpath="$(realpath "$0")"
prefix="$(dirname "${rpath}")/"
xdg="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
find "${prefix}"\
  ! -name "${self}"\
  ! -name "README.md"\
  ! -name "*_test" | while read -r dest
do
  c="${dest##"${prefix}"}"
  ln="${xdg}/${c}"
  if [[ -f "$dest" ]]; then
    case "$c" in
      exrc)       ln="${HOME}/.exrc";;
      gitconfig)  ln="${HOME}/.gitconfig";;
      profile)    ln="${HOME}/.profile";;
      inputrc)    ln="${HOME}/.inputrc";;
      tmux.conf)  ln="${xdg}/tmux.conf";;
      ssh/*)      ln="${HOME}/.$c";;
	    vim/*)		  ln="${HOME}/.$c";;
      *);;
    esac
    path="$(dirname "${ln}")"
    cmd="mkdir -p ${path} && ln -fs ${dest} ${ln}"
    if [[ -n "$PRINT_ONLY" ]]; then
      echo "$cmd"
    else
      eval "$cmd"
    fi
  fi
done
