#!/usr/bin/env bash
all=(NY SF-Pro SF-Mono SF-Arabic SF-Compact)
path="/usr/local/share/fonts"
cache="/tmp/fonts.${RANDOM}"
src="https://devimages-cdn.apple.com/design/resources/download"

if [[ "$(id -u)" -ne 0 ]]; then
  path="${XDG_DATA_HOME:-"$HOME/.local/share"}/fonts/apple"
  cache="${XDG_CACHE_HOME:-"$HOME/.cache"}/fonts.${RANDOM}"
fi

pkg() {
  7z x "$1.dmg" 1>/dev/null
  cd "${1//-/}Fonts"
  7z x "${1//-/ } Fonts.pkg" 1>/dev/null
  7z x 'Payload~' 1>/dev/null
  cp -f ./Library/Fonts/* "$2"
}

main() {
  mkdir -p "$cache" "$path"
  echo "Installing Monaco"
  cp -f ./monaco.ttf "$path/Monaco.ttf"

  cd "$cache"
  for name in "${all[@]}"; do
    echo "Installing $name"
    curl -sO "$src/$name.dmg"
    pkg "$name" "$path"
  done

  rm -rf "$cache"
}

main "$@"
