#!/bin/sh
set -e
self=${0##*/}

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

usage() {
	echo "usage: xorg/${0##*/} [-n]"
	exit 1
}

while getopts "n" opt; do
	case $opt in
	  n) PRINT_ONLY=1;;
	  *) usage;;
	esac
done

prefix="$(dirname `realpath $0`)"
find $prefix/ ! -name $self | while read src_abs; do
  src_rel=${src_abs##$prefix/}
  dest=$CONFIG_HOME/$src_rel
  if [ -d $src_abs ]; then
	[[ -n $PRINT_ONLY ]]\
	  && echo "mkdir -p $dest"\
	  || mkdir -p $dest
  else
	case $src_rel in
	  xsession) dest=$HOME/.xsession;;
	  xinitrc)
		  dest=$HOME/.xinitrc
		  src_abs=$HOME/.xsession;;
	esac
	[[ -n $PRINT_ONLY ]]\
	  && echo "ln -fs $src_abs $dest"\
	  || ln -fs $src_abs $dest
  fi
done
