#!/bin/sh
set -e
self="${0##*/}"

while getopts 'n' opt
do
  case "$opt" in
    n) PRINT_ONLY=1;;
    *) echo "usage: $self [-n]"; exit 1;;
  esac
done

prefix="$(dirname "$(realpath "$0")")/"
config_home="${XDG_CONFIG_HOME:-"$HOME/.config"}"
find "$prefix" ! -name "$self" ! -name "README.md" | while read -r target
do
  conf="${target##"$prefix"}"
  linkname="$config_home/$conf"
  if [ -f "$target" ]; then
    case "$conf" in
      fonts.conf)    linkname="$config_home/fontconfig/fonts.conf";;
      i3.conf)       linkname="$config_home/i3/config";;
      i3status.conf) linkname="$config_home/i3status/config";;
      xsession)      linkname="$HOME/.xinitrc";;
      gtk2.ini)      linkname="$HOME/.gtkrc-2.0";;
      gtk3.ini)      linkname="$HOME/gtk-3.0/settings.ini";;
    esac
    dir="$(dirname "$linkname")"
    cmd="mkdir -p $dir && ln -fs $target $linkname"
    [ -n "$PRINT_ONLY" ]\
      && echo "$cmd"\
      || eval "$cmd"
  fi
done
