#!/bin/sh
set -eu
while getopts 'n' opt
do
  case "$opt" in
    n) PRINT_ONLY=1;;
    *) echo "usage: term/$self [-n]"; exit 1;;
  esac
done

self="${0##*/}"
prefix="$(dirname "$(realpath "$0")")/"
config_home="${XDG_CONFIG_HOME:-"$HOME/.config"}"
find "$prefix" ! -name "$self" ! -name "README.md" | while read -r target
do
  conf="${target##"$prefix"}"
  linkname="$config_home/$conf"
  if [ -f "$target" ]; then
    case "$conf" in
      fonts.conf)    linkname="$config_home/fontconfig/fonts.conf";;
      i3.conf)       linkname="$config_home/i3/config";;
      i3status.conf) linkname="$config_home/i3status/config";;
      xsession)      linkname="$HOME/.xsession";;
      xinitrc)       linkname="$HOME/.xinitrc"
                     target="$HOME/.xsession";;
    esac
    dir="$(dirname "$linkname")"
    cmd="mkdir -p $dir && ln -fs $target $linkname"
    [ -n "$PRINT_ONLY" ]\
      && echo "$cmd"\
      || eval "$cmd"
  fi
done
