#!/bin/sh
export XCURSOR_SIZE=24
export XCURSOR_PATH=/usr/local/lib/X11/icons
export XCURSOR_THEME=whiteglass
export XWALLPAPER="$xprefix/../nier.jpg"
export SSH_ASKPASS="/usr/X11R6/bin/ssh-askpass"
export TERM=xterm-256color
export WM=i3
export TERMINAL=alacritty
