#!/bin/sh
# usage: xenv [dpi] []
export TERM=xterm-256color
export BROWSER=firefox
export READER=zathura
export WM=i3
export TERMINAL=kitty
export XWALLPAPER=$HOME/media/nier.jpg

dpi=${1:-96}
s=${2:-1}
export XCURSOR_SIZE=$((24*$s))
if [ $dpi -gt 96 ]
then
  export GDK_SCALE=2
  export GDK_DPI_SCALE=0.5
  export QT_AUTO_SCREEN_SCALE_FACTOR=1
else
  unset GDK_SCALE GDK_DPI_SCALE\
    QT_AUTO_SCREEN_SCALE_FACTOR
fi

if [ $uname -eq OpenBSD ]; then
  export XCURSOR_PATH=/usr/local/lib/X11/icons
  export XCURSOR_THEME=whiteglass
  export SSH_ASKPASS=/usr/X11R6/bin/ssh-askpass
fi

xrandr --dpi $dpi
