#!/bin/sh
export XCURSOR_SIZE=24
export XCURSOR_PATH=/usr/local/lib/X11/icons
export XCURSOR_THEME=whiteglass

xset b off
xset r rate 300 40

if [ 1 ]; then
	xset s off
	xset -dpms
	xset s noblank 

	xrandr --output eDP-1 --off
	xrandr --output DP-4 --mode 2560x1080 --rate 75 --dpi 82
	xrdb -merge $HOME/.config/x11/xresources
else
	export XCURSOR_SIZE=32
	xrandr --output eDP-1 --mode 2256x1504 --rate 60 --dpi 200
	xrdb -merge $HOME/.config/x11/xresources-hidpi
fi

xsetroot -solid '#1d2021'
exec dwm
