#!/bin/sh

xprefix="${XDG_CONFIG_HOME:-"$HOME/.config"}/x11"

Xdefaults="$xprefix/xdefaults"
Xresources="$xprefix/xresources"
XresourcesHidpi="$xprefix/xresources-hidpi"
Xcolors="$xprefix/xcolors"
Xwallpaper="$xprefix/../nier.png"

export XCURSOR_SIZE=24
export XCURSOR_PATH=/usr/local/lib/X11/icons
export XCURSOR_THEME=whiteglass
export SSH_ASKPASS="/usr/X11R6/bin/ssh-askpass"
export TERM=xterm-256color
export WM=i3

xset b off
xset r rate 256 32
xset s off
xset s noblank

[ -f $Xdefaults ] && xrdb -load $Xdefaults
[ -f $Xcolors ] && xrdb -load $Xcolors

if [ `xrandr --listactivemonitors | wc -l` -le 2 ]; then
	export GDK_SCALE=2
	export GDK_DPI_SCALE=0.5
	export QT_AUTO_SCREEN_SCALE_FACTOR=1
	export XCURSOR_SIZE=32

	[ -f $XresourcesHidpi ] && xrdb -merge $XresourcesHidpi
	xrandr --output eDP-1 --mode 2256x1504
	xrandr --dpi 200
else
	unset GDK_SCALE
	unset GDK_DPI_SCALE
	unset QT_AUTO_SCREEN_SCALE_FACTOR
	export XCURSOR_SIZE=24

	[ -f $Xresources ] && xrdb -merge $Xresources
	xrandr --output DP-4 --mode 2560x1080 --rate 75 --primary
	xrandr --output DP-3 --mode 2560x1440 --rate 75 --above DP-4
	xrandr --output eDP-1 --mode 2256x1504 --rate 60 --right-of DP-4
	xrandr --dpi 110
	setxkbmap de
fi

feh --no-fehbg --bg-fill $Xwallpaper &
ssh-agent $WM
