#!/bin/sh
cfg="${XDG_CONFIG_HOME:-"$HOME/.config"}"
Xdefaults="$cfg/x11/xdefaults"
Xresources="$cfg/x11/xresources"
XresourcesHidpi="$cfg/x11/xresources-hidpi"
Xcolors="$cfg/x11/xcolors"
Xenv="$cfg/xenv"
XenvHidpi="$cfg/xenv-hidpi"

_xrandr() {
  case $1 in
    desk) xrandr --dpi 108 --output DP-4-2 --mode 2560x1440 --rate 75 --primary --output DP-3 --mode 2560x1080 --rate 75 --above DP-4-2 --output eDP-1 --off; setxkbmap de;;
    port) xrandr --dpi 200 --output eDP-1 --mode 2256x1504 --rate 60 --primary;;
  esac
}

xset b off
xset r rate 256 32

[ -f $Xenv ] && source $Xenv
[ -f $Xdefaults ] && xrdb -load $Xdefaults
[ -f $Xcolors ] && xrdb -load $Xcolors
[ -f $Xresources ] && xrdb -load $Xresources

hidpi=0
if [ $hidpi -eq 1 ]; then
  [ -f $XenvHidpi ] && source $XenvHidpi
  [ -f $XresourcesHidpi ] && xrdb -merge $XresourcesHidpi
fi

docked=1
if [ $docked -eq 1 ]; then
  _xrandr desk
  xset s off
  xset s noblank
  xset -dpms
else
 _xrandr port
fi

ssh-agent $WM
