#!/usr/bin/env bash
set -e

all=(NY SF-Pro SF-Mono SF-Arabic SF-Compact)
path="/usr/local/share/fonts"
cache="/tmp/applefont"
src="https://devimages-cdn.apple.com/design/resources/download"

pkg() {
  7z x "$1.dmg" 1>/dev/null
  cd "${1//-/}Fonts"
  7z x "${1//-/ } Fonts.pkg" 1>/dev/null
  7z x 'Payload~' 1>/dev/null
  cp -f ./Library/Fonts/* "$cache"
}

main() {
  if [[ "$(id -u)" -ne 0 ]]; then
    path="${XDG_DATA_HOME:-"$HOME/.local/share"}/fonts/apple"
    cache="${XDG_CACHE_HOME:-"$HOME/.cache"}/applefont"
  fi

  case "$1" in
    i|install)
      [[ -e "$cache" ]] && rm -r "$cache"
      mkdir -p "$cache" "$path"
      cd "$cache"
      for name in "${all[@]}"; do
        echo "Installing $name"
        curl -sO "$src/$name.dmg" && pkg "$name" "$path"
      done;;
    *)
      echo "usage: applefont [i|install]"
      return;;
  esac
}

main "$@"
