#!/usr/bin/env bash
set -e

main() {
  if [[ -z "${DISPLAY}" ]]; then
    echo "duh"
    exit 1
  fi

  if [[ -z "$XAUTHORITY" ]]; then
    echo "duhhhh"
    exit 1
  fi

  case "$1" in
    *) echo "[$(date)]: conf" >> /tmp/log;;
  esac
}

main "$@"
