#!/usr/bin/env bash
# designed for bash 4.0+

case $- in
  *i*) ;; # interactive
  *) return ;;
esac

__git_prompt() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

set -o vi
bind -x '"\C-l": clear;'
# clipboard interaction
alias xcopy="xclip -selection c"
alias xpaste="xclip -selection c -o"

# overload defaults
alias act="act -P self-hosted=node:16-buster-slim"
alias cp="cp -ir"
alias tree="exa -@ --tree"
alias rm="rm -i"
alias mv="mv -i"
alias vi="vim"
alias tmux="tmux -uf ~/.config/tmux.conf"
alias more="less -R"

if [[ $(uname) = Linux ]]; then
  alias ls='ls --color=always'
fi

# TODO: Human-readable PS1
PROMPT_DIRTRIM=2
export PS1="\[\e[49;93m\]\u\[\e[49;37m\]@\[\e[49;38;5;36m\]\h\[\e[49;37m\]:\w\$(__git_prompt)\$\[\e[49;39m\] "

export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_BIN_HOME="${HOME}/.local/bin"

export EDITOR=vim
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export GOPATH="${XDG_DATA_HOME}/go"
export GOBIN="${XDG_BIN_HOME}"
export GPG_TTY="$(tty)"

pathappend() {
  for arg in "$@"; do
    test -d "$arg" || continue
    arg=${arg%%/}
    PATH=${PATH//":$arg:"/:}
    PATH=${PATH#"$arg:"}
    PATH=${PATH%":$arg"}
    export PATH="${PATH:+"$PATH:"}$arg"
  done
}

pathprepend() {
  for arg in "$@"; do
    test -d "$arg" || continue
    arg=${arg%%/}
    PATH=${PATH//":$arg:"/:}
    PATH=${PATH#"$arg:"}
    PATH=${PATH%":$arg"}
    export PATH="$arg${PATH:+":$PATH"}"
  done
}

pathprepend /bin\
  /sbin\
  /usr/bin\
  /usr/local/bin\
  /usr/local/sbin\
  "${XDG_BIN_HOME}"\
  "${GOBIN:-"$GOPATH/bin"}"\
  "${HOME}/.cargo/bin"\
  /usr/bin/core_perl

# Stop history from saving duplicate commands
# and commands that begin with leading space
export HISTCONTROL=ignoreboth
export HISTSIZE=4096          # in memory
export HISTFILESIZE=8192      # on disk
export LESS="-R"

# Append history[HISTSIZE] to history file on disk
shopt -s histappend

# Prevent Ctrl-s from stopping the terminal
stty stop undef

shopt -s checkwinsize
shopt -s expand_aliases
shopt -s globstar
shopt -s dotglob
shopt -s extglob


t() {
  local src="${SRCDIR:-"$HOME/src"}"
  local depth=3

  if [ -n "$1" ]; then
    local rel="$(cd "$src"\
      && find . -maxdepth $depth -type d -name "$1" -print\
      | sed 's/\.\///g')"
  else
    local rel="$(cd "$src"\
      && find . -mindepth $depth -maxdepth $depth -type d -print\
      | sed 's/\.\///g'\
      | fzf)"
  fi

  [[ -z "$rel" ]] && return
  local dir="$src/$rel"
  local sess="$(basename "$rel" | sed 's/\./_/g')"

  tmux has-session -t "$sess" 2>/dev/null
  if [[ $? -eq 1 ]]; then
    tmux start-server
    tmux new-session -c "$dir" -ds "$sess"
  fi
  tmux attach -t "$sess"
}

m(){
  [[ -z "$@" ]] && return
  eval "$@" | less -R
}

path() {
  echo -e ${PATH//:/\\n}
}

xhi() {
  xrandr --dpi 200\
    --output eDP1 --primary --auto\
    --output DP4-2 --off
  xrdb -merge "$XDG_CONFIG_HOME/xhidpi"
  i3-msg restart 2>&1 >/dev/null
}

xopt() {
  xrandr --dpi 96\
    --output eDP1 --primary --auto\
    --output DP3 --off
  xrdb -merge "$XDG_CONFIG_HOME/xresources.dp3"
  i3-msg restart 2>&1 >/dev/null
}

xlo() {
  xrandr --dpi 108\
    --output DP4-2 --primary --auto --above eDP1\
    --output eDP1 --auto
  xset s off
  xset s noblank
  xset -dpms
  xrdb -merge "$XDG_CONFIG_HOME/xdefaults"
  i3-msg restart 2>&1 >/dev/null
}
