#!/bin/sh
set -e

if [ "$(tput colors)" -ge 8 ]; then
  term_yellow="\033[0;33m"
  term_reset="\033[0;00m"
fi

usage() {
  printf "%s(%d)\n" setup 1
  printf "${term_yellow}%s${term_reset}\n\t%s\n\n"\
    NAME "name - a wonderful tool"
  printf "${term_yellow}%s${term_reset}\n\t%s\n\n"\
    SYNOPSIS "setup [-hn]"
  printf "\tname is a really great programm and is meant to replace\n\
    \tany other existing program. Really."
  printf "\n"
}

while getopts "nh" opt
do
  case "${opt}" in
    n) PRINT_ONLY=1;;
    h) usage; exit 0;;
    *) usage; exit 1;;
  esac
done

self="${0##*/}"
rpath="$(realpath "$0")"
prefix="$(dirname "${rpath}")/"
confd="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
find "${prefix}" ! -name "${self}" ! -name "README.md"\
  ! -name "*_test" | while read -r target
do
  conf="${target##"${prefix}"}"
  linkname="${confd}/${conf}"
  if [ -f "${target}" ]; then
    case "${conf}" in
      exrc)         linkname="${HOME}/.exrc";;
      gitconfig)    linkname="${HOME}/.gitconfig";;
      profile)      linkname="${HOME}/.profile";;
      ssh.conf)     linkname="${HOME}/.ssh/config";;
      inputrc)     linkname="${HOME}/.inputrc";;
      tmux.conf)    linkname="${confd}/tmux.conf";;
	  vim/*)		linkname="${HOME}/.${conf}";;
      *);;
    esac
    dir="$(dirname "${linkname}")"
    cmd="mkdir -p ${dir} && ln -fs ${target} ${linkname}"
    if [ -n "${PRINT_ONLY}" ]
    then
      echo "${cmd}"
    else
      eval "${cmd}"
    fi
  fi
done
