#!/bin/sh
set -e

rc() {
  [ -n "$PRINT_ONLY" ]\
    && echo "$1"\
    || eval "$1"
}

self="${0##*/}"
prefix="$(dirname $(realpath $0))"
while getopts "nxd:" opt; do
  case "$opt" in
  n) PRINT_ONLY=1;;
  x) WITH_XORG=1;;
  d) DISTRO=$OPTARG;;
  *) echo "usage: $self [-nx] [-d distribution]"; exit 1;;
  esac
done

user="${DOAS_USER:=$USER}"
uname="$(uname)"
pkglist="$prefix/${DISTRO:="$uname"}${WITH_XORG+-xorg}.list"
case "$uname" in
  OpenBSD) pkg="pkg_add -IUl $pkglist";;
  Linux)
    case "$DISTRO" in
      arch*) pkg="xargs -a pacman -Syyuu --needed --noconfirm";;
      *) echo "Warning: Unsupported Linux variant ($LINUXDIST), skipping package install";; 
    esac;;
  *) echo "Warning: Unsupported Operating System ($uname), skipping package install";;
esac

[ $(id -u) -eq 0 ]\
  && { rc "$pkg"; }\
  || { echo "Warning: Running as normal user, skipping package install"; }

rc "python3 -m pip install --user -r $prefix/pip3.list"
rc "nvim +qall"
